import {
  faCheckSquare,
  faCoffee,
  faHome,
  faChevronLeft,
  faMicrophone,
  faMicrophoneAlt,
  faAssistiveListeningSystems,
  faUser,
  faPlay,
  faPause,
  faTimes,
  faSearch,
  faExclamationCircle,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faPlusCircle,
  faBookmark,
  faHeart,
  faClock,
  faEyeSlash,
  faEye,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBookmark as farBookmark,
  faHeart as farHeart,
  faClock as farClock,
  faCircle,
} from '@fortawesome/free-regular-svg-icons';

export const iconList = {
  farBookmark,
  farHeart,
  farClock,
  faCheckSquare,
  faCoffee,
  faHome,
  faChevronLeft,
  faMicrophone,
  faMicrophoneAlt,
  faAssistiveListeningSystems,
  faUser,
  faClock,
  faPlay,
  faPause,
  faTimes,
  faHeart,
  faSearch,
  faBookmark,
  faExclamationCircle,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faPlusCircle,
  faCircle,
  faEyeSlash,
  faEye,
};
export type Icons = keyof typeof iconList;
